const {test}=require('node:test'),assert=require('node:assert/strict');
const M=require('../js/model'),S=require('../js/simulation'),A=require('../js/sensitivity');
const {base,cdf}=require('./fixtures/quality.cjs');
const {mission}=require('./fixtures/all-cdf.cjs');
function run(d,options={}){const job=A.createAllCDF(d,{iterations:128,steps:3,seed:13,...options});let status;do{status=job.step(32);}while(!status.done);assert.equal(status.completed,status.total);return job.result();}
test('automatic analysis discovers all enabled Task and causal CDFs, ranks effects and preserves source',()=>{const d=mission(),before=M.clone(d),r=run(d);assert.equal(r.targets.length,3);assert.deepEqual(r.targets.map(t=>t.key),['task:produce','task:consume','causalLink:report']);assert(r.targets[0].improvement>0);assert(r.targets[2].improvement>0);assert.equal(r.targets[1].improvement,0);const row=r.targets.find(t=>t.key===r.ranking[0]);assert.equal(row.improvement,Math.max(...r.targets.map(t=>t.improvement)));for(const t of r.targets){assert.deepEqual(t.points.map(p=>p.q),[0,.5,1]);assert(t.points.every(p=>p.interval95.low<=p.probability&&p.probability<=p.interval95.high));}assert.deepEqual(d,before);});
test('quality intervention on a causal CDF preserves emission and propagates intervened quality',()=>{const d=mission();const c=S.compile(d,{linkOverrides:{report:{q:1}},taskOverrides:{produce:{q:1}}});const r=S.trial(c,()=>.2);assert.equal(r.signalEvents[0].q,1);assert.equal(r.stateQ.get('r0'),1);assert.equal(r.taskTimes.get('consume').q,1);assert(r.success);assert.throws(()=>S.compile(d,{linkOverrides:{missing:{q:1}}}),/不正/);assert.throws(()=>S.compile(d,{linkOverrides:{report:{q:2}}}),/範囲/);});
test('paired analysis is deterministic across repeated runs and batch sizes',()=>{const d=mission(),one=run(d),two=run(d);assert.deepEqual(one,two);const job=A.createAllCDF(d,{iterations:128,steps:3,seed:13});while(!job.step(7).done){}assert.deepEqual(job.result(),one);});
test('disabled and fixed models are excluded; empty scope and excessive workload are rejected',()=>{const d=mission();d.causalLinks[0].simulation.enabled=false;assert.equal(A.cdfTargets(d).length,2);assert.throws(()=>A.createAllCDF(base()),/CDFがありません/);assert.throws(()=>A.createAllCDF(mission(),{steps:26}),/評価点数/);assert.throws(()=>A.createAllCDF(mission(),{iterations:100000,steps:25}),/処理量/);});
