const {test}=require('node:test'),assert=require('node:assert/strict');const {openApp}=require('./dom-helper.cjs'),{base,gate}=require('./fixtures/quality.cjs');
async function app(t,d=base()){const a=await openApp(d);t.after(()=>a.close());return a;}
test('fresh v3 document renders all State/Task elements without obsolete polarity UI',async t=>{const a=await app(t);assert.equal(a.$('.legend').textContent.includes('正の作用'),false);assert.equal(a.$('[data-id="s0"]')!==null,true);assert.equal(a.w.IMEE.getDocument().version,3);assert.deepEqual(a.errors,[]);});
test('State edit saves quality and supports undo/redo',async t=>{const a=await app(t);a.event(a.$('.state[data-id="s0"]'),'dblclick');a.fill('stateQ',.5);a.submit();assert.equal(a.savedDoc().states[0].simulation.q,.5);a.w.IMEE.undo();assert.equal(a.w.IMEE.getDocument().states[0].simulation.q,.8);a.w.IMEE.redo();assert.equal(a.savedDoc().states[0].simulation.q,.5);});
test('State to same-Actor State creates Task and opens its quality editor',async t=>{const a=await app(t);a.click('.state[data-id="s0"]');a.key('c');a.click('.state[data-id="s1"]');assert.equal(a.w.IMEE.getDocument().tasks.length,3);assert(a.$('[name="qualityRetention"]'));assert.equal(a.$('[name="waitForWLinks"]'),null);});
test('State to different-Actor State creates causal link with only permitted endpoints',async t=>{const a=await app(t);a.click('.state[data-id="s0"]');a.key('c');a.click('.state[data-id="r0"]');assert(a.$('[name="causalDelay"]'));assert.equal(a.$('[name="polarity"]'),null);assert([...a.$('[name="source"]').options].every(o=>o.value.startsWith('state:')));a.submit();assert.equal(a.savedDoc().causalLinks.length,2);});
test('Task and Actor cannot be causal sources',async t=>{const a=await app(t);for(const selector of ['.edge.task[data-id="produce"]','.actor[data-id="a"]']){a.click(selector);a.key('c');assert(a.$('#status').textContent.includes('起点はState'));}assert.equal(a.w.IMEE.getDocument().causalLinks.length,1);});
test('State can connect to an exact existing junction; causal editor chooses explicit outcome',async t=>{const a=await app(t,gate());a.click('.state[data-id="effect"]');a.key('c');a.click('.junction[data-junction-id="point"]');assert(a.$('[name="causalOutcome"]'));a.submit();const c=a.savedDoc().causalLinks.at(-1);assert.equal(c.target.type,'junction');assert.equal(c.target.id,'point');assert.equal(c.target.taskId,'flight');assert.equal(c.target.outcomeStateId,'killed');});
test('arbitrary Task attachment is rejected with useful message and no model mutation',async t=>{const a=await app(t);a.click('.state[data-id="s0"]');a.key('c');a.click('.edge.task[data-id="consume"]');assert.equal(a.w.IMEE.getDocument().causalLinks.length,1);assert(a.$('#status').textContent.includes('既存の分岐点'));});
test('view settings show implicit dependencies without changing the mission graph',async t=>{const a=await app(t,gate());a.click('#view-settings');a.fill('implicitDependencies','true');a.submit();assert(a.$('.implicit-dependency'));assert.equal(a.w.IMEE.getDocument().causalLinks.length,1);assert.equal(a.w.IMEE.getDocument().tasks.length,2);});
test('invalid JSON is drawn with detailed offending object in a callout',async t=>{const a=await app(t);const d=base();d.causalLinks[0].polarity='negative';a.w.IMEE.loadJSON(JSON.stringify(d));assert(a.$('.import-error').textContent.includes('polarity'));assert(a.$('[data-id="report"]'));assert.deepEqual(JSON.parse(JSON.stringify(a.w.IMEE.getDocument())),d);});
