const {test}=require('node:test'),assert=require('node:assert/strict');
const D=require('../js/import-diagnostics'),L=require('../js/layout'),R=require('../js/render');
const {base}=require('./fixtures/quality.cjs'),{openApp}=require('./dom-helper.cjs');
test('invalid timing still draws the original positions and a located diagnostic',()=>{const d=base();d.causalLinks[0].propagation.duration=4;const r=D.inspect(JSON.stringify(d)),g=L.layout(r.document);assert(r.errors.length);assert.equal(r.document.causalLinks[0].propagation.duration,4);assert(D.bubbles(r,g,R.esc).includes('data-error-path="$.states[2]"'));assert.deepEqual(r.original,d);});
test('dangling references omit only undrawable edges and retain their original JSON',()=>{const d=base();d.tasks[1].fromStateId='missing';d.causalLinks[0].target.id='missing';const r=D.inspect(JSON.stringify(d));assert.equal(r.document.tasks.length,1);assert.equal(r.document.causalLinks.length,0);assert.equal(r.document.states.length,4);assert(r.errors.some(e=>e.path==='$.causalLinks[0]'));assert(R.render(r.document,L.layout(r.document)).includes('s1'));assert.deepEqual(r.original,d);});
test('missing collections, invalid ranges and cyclic Actor parents cannot crash diagnostic layout',()=>{for(const d of [{version:3,title:'bad'}, {...base(),time:{duration:-1},actors:[{id:'a',parentId:'b'},{id:'b',parentId:'a'}]}, {...base(),states:'bad'}]){const r=D.inspect(JSON.stringify(d));assert(r.errors.length);assert.doesNotThrow(()=>R.render(r.document,L.layout(r.document)));}});
test('malformed JSON is rejected without fabricating a diagram',()=>{assert.throws(()=>D.inspect('{bad'));assert.throws(()=>D.inspect('null'));});
test('import keeps source, shows callouts, preserves saved valid data and Undo restores prior document',async t=>{const d=base(),a=await openApp(d);t.after(()=>a.close());const bad=structuredClone(d);bad.tasks[1].fromStateId='missing';a.w.IMEE.loadJSON(JSON.stringify(bad));assert(a.$('.import-error'));assert(a.$('#simulation-btn').disabled);assert(a.$('[data-id="produce"]'));assert(a.$('#status').textContent.includes('診断表示'));assert.deepEqual(JSON.parse(JSON.stringify(a.w.IMEE.getDocument())),bad);assert.deepEqual(a.savedDoc(),d);a.w.IMEE.undo();assert.equal(a.$('.import-error'),null);assert.deepEqual(a.errors,[]);});
test('invalid cached document opens diagnostic preview and a subsequent valid import clears it',async t=>{const d=base();d.causalLinks[0].target.id='missing';const a=await openApp(d);t.after(()=>a.close());assert(a.$('.import-error'));a.w.IMEE.loadJSON(JSON.stringify(base()));assert.equal(a.$('.import-error'),null);assert.deepEqual(a.errors,[]);});

test('diagnostic JSON is escaped and cannot inject SVG or HTML',()=>{const d=base();d.causalLinks[0].target.id='<script>alert(1)</script>';const r=D.inspect(JSON.stringify(d)),html=D.bubbles(r,L.layout(r.document),R.esc);assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'));});
