const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../js/model');
const {base,gate}=require('./fixtures/quality.cjs');
test('v3 roundtrip, history and quality references survive undo/redo',()=>{const d=base(),h=new M.History(d);assert.deepEqual(M.parse(JSON.stringify(d)),d);const n=M.clone(d);n.title='new';h.commit(n);h.undo();assert.equal(h.doc.title,d.title);h.redo();assert.equal(h.doc.title,'new');});
for(const [label,mutate] of [
 ['v2',d=>d.version=2],['polarity',d=>d.causalLinks[0].polarity='positive'],['Task source',d=>d.causalLinks[0].source={type:'task',id:'produce',time:5}],['Actor source',d=>d.causalLinks[0].source={type:'actor',id:'a',time:0}],['Task target',d=>d.causalLinks[0].target={type:'task',id:'consume'}],['target.time',d=>d.causalLinks[0].target.time=10],['old w',d=>d.states[0].simulation.w=0],['old type',d=>d.causalLinks[0].simulation.type='state'],['negative duration',d=>d.causalLinks[0].propagation.duration=-1],['duplicate',d=>d.states[1].id='s0'],['cross Actor',d=>d.tasks[0].toStateId='r1'],['fixed Task q',d=>d.tasks[0].simulation.q=.5]
])test('reject '+label+' with JSON context',()=>{const d=base();mutate(d);assert.throws(()=>M.validate(d),e=>!!e.validationPath && e.validationFragment!==undefined);});
test('all outcome and junction references are checked even in scenario-only documents',()=>{const d=gate();d.causalLinks[0].simulation.enabled=false;d.causalLinks[0].target.outcomeStateId='missing';assert.throws(()=>M.validate(d),/結果State/);});
test('state-only connections build Tasks or causal State connections; arbitrary ports are rejected',()=>{const d=base();M.createConnection(d,{type:'state',id:'s0'},{type:'state',id:'s1'});assert.throws(()=>M.createConnection(d,{type:'state',id:'s0'},{type:'task',id:'consume',time:15}),/State起点/);});
test('recursive copy remaps junction IDs, target Task and outcome State; gates are derived',()=>{const d=gate();const f=M.fragment(d,d.actors.map(a=>({type:'actor',id:a.id})));M.paste(d,f,40);const c=d.causalLinks[1];assert.notEqual(c.target.taskId,'flight');assert.notEqual(c.target.id,'point');assert.notEqual(c.target.outcomeStateId,'killed');assert(M.get(d,'task',c.target.taskId).junctions.some(j=>j.id===c.target.id));assert.equal(M.implicitDependencies(d).length,2);});
test('deleting an outcome removes its branch action; removing a State cleans quality input refs',()=>{const d=gate();M.remove(d,[{type:'state',id:'killed'}]);assert.equal(d.causalLinks.length,0);const n=base();n.tasks[1].simulation.qInput={stateIds:['s0'],mode:'all'};M.remove(n,[{type:'state',id:'s0'}]);assert.deepEqual(n.tasks[0].simulation.qInput.stateIds,[]);});
test('implicit start cycles give dependency path and related JSON',()=>{const d=gate();d.tasks[0].fromStateId='effect';d.states.find(s=>s.id==='effect').actorId='e';d.tasks=d.tasks.filter(t=>t.id!=='action');d.states.find(s=>s.id==='end').time=40;assert.throws(()=>M.validate(d),e=>e.message.includes('循環') && e.validationFragment.cycle.some(id=>id==='start:flight'));});
