const { test } = require("node:test"), assert = require("node:assert/strict");
const { openApp } = require("./dom-helper.cjs"), fixture=require("./fixtures/simulation.cjs");
async function app(t,d=fixture()) {
  const a=await openApp(d);
  t.after(()=>{assert.deepEqual(a.errors,[]);a.close();}); return a;
}
async function wait(a,predicate) {
  const deadline=Date.now()+5000;
  while (!predicate()) { if(Date.now()>deadline) throw new Error("Timed out"); await new Promise(r=>a.w.setTimeout(r,5)); }
}
test("second native click opens Task performance even when SVG redraw suppresses dblclick",async t=>{
  const a=await app(t);
  a.event(a.$('[data-id="detect"].task-label text'),"pointerdown");
  a.event(a.$('[data-id="detect"].task-label text'),"click",{detail:2});
  assert.equal(a.$("#dialog-title").textContent,"Task");
  assert(a.$("#editor-dialog").open);
  assert(a.$(".simulation-performance"));
  const field=a.$('[name="label"]');
  field.value="入力を維持";
  a.event(a.$('[data-id="detect"]'),"dblclick");
  assert.equal(a.$('[name="label"]').value,"入力を維持");
});
test("performance editor edits CDF graph and table, keeps disabled curves, saves dependencies and Undo",async t=>{
  const a=await app(t);
  a.event(a.$('[data-id="detect"]'),"dblclick");
  assert(a.$("#cdf-preview svg"));
  a.fill("curve-0-p-1",.7);
  a.event(a.$('[name="curve-0-p-1"]'),"input");
  assert(a.$("#cdf-preview svg"));
  a.fill("performanceW",.5);
  a.submit();
  assert.equal(a.savedDoc().tasks[0].simulation.performanceModel.curves[0].points[1].p,.7);
  assert.equal(a.savedDoc().tasks[0].simulation.w,.5);
  a.w.IMEE.undo();
  assert.equal(a.savedDoc().tasks[0].simulation.w,0);
  a.event(a.$('[data-id="detect"]'),"dblclick");
  a.$('[name="performanceEnabled"]').checked=false;
  a.event(a.$('[name="performanceEnabled"]'),"change");
  assert(a.$("#performance-cdf-fields").disabled);
  a.submit();
  assert.equal(a.savedDoc().tasks[0].simulation.enabled,false);
  assert(a.savedDoc().tasks[0].simulation.performanceModel);
  a.event(a.$('[data-id="act"]'),"dblclick");
  assert(a.$('[name="waitForStateIds"][value="s1"]').checked);
  a.$('[name="waitForStateIds"][value="s1"]').checked=false;
  a.submit();
  assert.deepEqual(a.savedDoc().tasks[1].simulation.waitForStateIds,[]);
  // Earlier Task editor listeners must not leak into a subsequent State dialog.
  a.event(a.$('[data-id="s0"]'),"dblclick");
  a.event(a.$('[name="name"]'),"input");
});
test("invalid CDF edit is rejected without replacing saved data; point and curve controls work",async t=>{
  const a=await app(t), before=a.savedDoc();
  a.event(a.$('[data-id="detect"]'),"dblclick");
  a.fill("curve-0-p-1",.1);
  a.event(a.$('[name="curve-0-p-1"]'),"input");
  assert(a.$("#cdf-preview-error").textContent.includes("単調"));
  a.submit();
  assert(a.$("#dialog-error").textContent);
  assert.deepEqual(a.savedDoc(),before);
  a.fill("curve-0-p-1",.6);
  a.click("#add-cdf-curve");
  assert.equal(a.d.querySelectorAll("[data-curve]").length,3);
  a.click('[data-add-point="0"]');
  assert.equal(a.d.querySelectorAll('[data-curve="0"] [data-point]').length,4);
  a.click('[data-remove-point="0-3"]');
  a.click('[data-remove-curve="1"]');
  a.submit();
  assert.equal(a.savedDoc().tasks[0].simulation.performanceModel.curves.length,2);
});
test("Monte Carlo displays results, exports reproducible snapshot, invalidates changed mission but keeps View results",async t=>{
  const a=await app(t);
  a.click("#simulation-btn"); a.click("#simulation-run");
  await wait(a,()=>!a.$("#simulation-export").disabled);
  assert(a.$("#simulation-results").textContent.includes("Mission成功率"));
  assert(a.$("#simulation-results svg"));
  a.click("#simulation-export");
  const download=a.downloads.at(-1);
  assert.equal(download.name,"mission-simulation.json");
  const data=JSON.parse(await a.readBlob(download.blob));
  assert.equal(data.result.iterations,2000);
  assert.equal(data.mission.simulation.seed,17);
  assert.deepEqual(data.result,JSON.parse(JSON.stringify(a.w.MESimulation.run(data.mission))));
  a.click("#simulation-close");
  a.click("#zoom-in"); a.click("#simulation-btn");
  assert.equal(a.$("#simulation-export").disabled,false);
  a.click("#simulation-close");
  a.event(a.$('[data-id="detect"]'),"dblclick");
  a.fill("curve-0-p-1",.65);a.submit();
  a.click("#simulation-btn");
  assert(a.$("#simulation-export").disabled);
  assert.equal(a.$("#simulation-results").textContent,"");
});
test("settings save all selected success States, deadline and integer seed, and are undoable",async t=>{
  const a=await app(t);
  a.click("#simulation-btn"); a.click("#simulation-configure");
  a.$('[name="successStateIds"][value="s1"]').checked=true;
  a.fill("successMode","any");
  a.fill("deadline",40);a.fill("iterations",1500);a.fill("seed",12);
  a.submit();
  await wait(a,()=>a.$("#simulation-dialog").open);
  assert.deepEqual(a.savedDoc().simulation.successStateIds,["s1","c1"]);
  assert.equal(a.savedDoc().simulation.deadline,40);
  assert.equal(a.savedDoc().simulation.successMode,"any");
  assert(a.$("#simulation-setup").textContent.includes(" OR "));
  a.click("#simulation-close"); a.w.IMEE.undo();
  assert.equal(a.savedDoc().simulation.deadline,45);
  a.click("#simulation-btn");a.click("#simulation-configure");
  for(const input of a.d.querySelectorAll('[name="successStateIds"]')) input.checked=false;
  a.submit();
  assert(a.$("#dialog-error").textContent.includes("成功State"));
});
test("run can be cancelled; unsupported branches report an error; demo preserves undo",async t=>{
  const d=fixture();d.simulation.iterations=100000;
  const a=await app(t,d);
  a.click("#simulation-btn");a.click("#simulation-run");a.click("#simulation-stop");
  await new Promise(r=>a.w.setTimeout(r,30));
  assert(a.$("#simulation-progress").textContent.includes("中断"));
  assert(a.$("#simulation-export").disabled);
  a.click("#simulation-demo");a.submit();
  await wait(a,()=>a.$("#simulation-dialog").open);
  assert.equal(a.savedDoc().title,"Simulation — 検出と並列準備");
  a.click("#simulation-close");a.w.IMEE.undo();
  assert.equal(a.savedDoc().title,d.title);
  const branched=fixture();branched.tasks[0].junctions=[{id:"j",time:5,outcomes:[{label:"NG",toStateId:"s1"}]}];
  a.w.IMEE.loadJSON(JSON.stringify(branched));
  a.click("#simulation-btn");a.click("#simulation-run");
  assert(a.$("#simulation-error").textContent.includes("分岐Task"));
  assert(a.$("#simulation-export").disabled);
});
