const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../js/model');
const {gate,trial,state,task,link,cdf}=require('./fixtures/quality.cjs');
test('early sampled result waits for the actual target start including its additional condition',()=>{const r=trial(gate(),.05);assert.equal(r.taskTimes.get('action').end,1);assert.equal(r.taskTimes.get('flight').start,15);assert.equal(r.times.get('effect'),15);assert.equal(r.signalEvents[0].emittedAt,15);assert.equal(r.signalEvents[0].time,16);assert.equal(r.taskTimes.get('flight').status,'branched');assert.equal(r.stateQ.get('effect'),.8);assert.equal(r.stateQ.get('killed'),.8);});
test('source OR cannot bypass the mandatory target start gate',()=>{const d=gate();d.states.find(s=>s.id==='effect').simulation={join:'any'};assert.equal(trial(d,.05).times.get('effect'),15);});
test('a cancelled target never starts: gated State and action never emit',()=>{const d=gate();d.states.push(state('cancel','e',0));d.tasks[0].simulation.cancelOnStateIds=['cancel'];const r=trial(d,.05);assert.equal(r.taskTimes.get('flight').status,'cancelled');assert.equal(r.times.get('effect'),Infinity);assert.equal(r.signalEvents.length,0);});
test('a late effect is nonapplicable and cannot create a kill State',()=>{const d=gate();d.tasks[1].simulation.performanceModel=cdf([{t:40,p:1,q:1}]);const r=trial(d,.99);assert.equal(r.signalEvents[0].status,'late');assert.equal(r.times.get('killed'),Infinity);});
test('effect exactly at target completion wins before ordinary continuation',()=>{const d=gate();d.tasks[1].simulation={enabled:false};d.states.find(s=>s.id==='effect').time=29;d.tasks[0].junctions[0].time=30;d.states.find(s=>s.id==='killed').time=30;const r=trial(d);assert.equal(r.signalEvents[0].status,'accepted');assert.equal(r.times.get('end'),Infinity);assert.equal(r.times.get('killed'),30);});
test('blocked additional target prerequisite blocks the effect even when S has a result',()=>{const d=gate();d.states.push(state('condition-source','e',0));d.causalLinks.push(link('required','condition-source','condition',15));d.causalLinks.at(-1).propagation.performanceModel=cdf([{t:15,p:0,q:1}]);const r=trial(d);assert.equal(r.taskTimes.get('flight').status,'blocked');assert.equal(r.times.get('effect'),Infinity);});
test('all target Tasks must start when one State is shared by multiple branch effects',()=>{const d=gate();d.states.find(s=>s.id==='effect').time=35;d.states.push(state('launch2','e',30),state('end2','e',60),state('killed2','e',36));d.tasks.push(task('flight2','launch2','end2'));d.tasks.at(-1).junctions=[{id:'point2',time:36,outcomes:[{label:'kill2',toStateId:'killed2',delay:0}],simulation:{mode:'effect'}}];d.tasks[0].junctions[0].time=36;d.states.find(s=>s.id==='killed').time=36;d.states.find(s=>s.id==='end').time=50;d.causalLinks.push(link('hit2','effect',{type:'junction',taskId:'flight2',id:'point2',outcomeStateId:'killed2'},1));assert.equal(trial(d,.05).times.get('effect'),30);});
